.github/workflows/check-and-release-main.yml
.github/workflows/pull-request.yml
README.md
setup.py
tox.ini

Closes issue #2 without making Python 3.10 a required minimum. However, enabling support for 3.10 necessitates updating to [Sphinx v4.2.0](https://www.sphinx-doc.org/en/master/changes.html#release-4-2-0-released-sep-12-2021).
@novikovav, what’s your experience wrt. performance when using [actions/cache](https://github.com/actions/cache) to [cache dependent packages during workflows](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#caching-dependencies)?

ci: add support for Python 3.10

---

UPSTREAM_README.md
setup.py
src/package/__init__.pyi
src/package/something.pyi

Closes #54 and adds [PEP 561](https://www.python.org/dev/peps/pep-0561/) compatible type stubs so that `mypy` is able to check code which imports this package correctly.
I’ve tested this by creating an external test venv and `pip install`ed this cookiecutter template package. Without the changes of this PR I get
```
(TEST) savage@pooh ~/opt/dev/TEST > mypy test.py 
test.py:1: error: Skipping analyzing "package.something": found module but no type hints or library stubs
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
test.py:1: error: Skipping analyzing "package": found module but no type hints or library stubs
Found 2 errors in 1 file (checked 1 source file)
```
whereas with this change
```
(TEST) savage@pooh ~/opt/dev/TEST > mypy test.py …
```

feat: add type stubs for the example package

---

.github/workflows/pull-request.yml
.pre-commit-config.yaml
MANIFEST.in
UPSTREAM_README.md
mypy.ini
setup.py
tox.ini

As we’re using the repository for various projects, we continue to find details that need tweaking… so here’s the first batch of ’em 🤓

chore: tweak project settings

---

.github/workflows/check-and-release-main.yml
UPSTREAM_README.md
setup.py

This PR closes #62 but I wanted to discuss some more. Specifying
https://github.com/jenstroeger/python-package-template/blob/de5c51b08c6bd97880cc24594a928e19c5932ecb/.github/workflows/check-and-release-main.yml#L44
doesn’t actually _pin_ a version and instead every run of this Action uses whatever changes are at the head of the `master` branch. That, I think, violates some of the [SLSA build requirements](https://slsa.dev/requirements#build-requirements) like “Reproducible”.
📌 it?

ci: remove unnecessary semantic-release tool from dev environment

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml
UPSTREAM_README.md

This PR enables Codeql for analyzing the python code in `src/package` directory. The current settings force the scan for PRs and `push`es to the `main` and `staging` branches. It's also scheduled to run once a week. It does not trigger on PRs that only modify `.txt` or `.md` files.
Note that Codeql is not supported in private repositories by default.

feat: enable codeql security analyzer

---

mypy.ini

By removing `exclude=` mypy can find the files again and the CI should pass.
This PR also updates the Python version to `3.10`.

fix: remove exclude from mypy.ini and update version

---

tox.ini

I think it makes sense to _always_ show certain runtime exceptions, e.g. a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). We may want to document this, and we may consider using the [-W](https://docs.python.org/3/using/cmdline.html#cmdoption-W) option to raise exceptions and actually fail a `tox` run?

chore: make sure to always show certain warnings when running tox

---

.pre-commit-config.yaml
UPSTREAM_README.md
pyproject.toml
setup.py

As mentioned in issue #5 I added the [bandit](https://bandit.readthedocs.io/) tool as a pre-commit hook.
I do have a few concerns though:
- There are currently 146 open issues and 48 open pull requests, and progress seems sluggish.
- `pyproject.toml` configuration isn’t currently supported (issue https://github.com/PyCQA/bandit/issues/733) but seems to have been committed to mainstream (commit https://github.com/PyCQA/bandit/commit/44f5c416cc0b7d62ca55b78e90bd1f7ee3d16082) but I couldn’t make that work.
- Our unit tests make explicit use of the [assert](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement) statement which is flagged by `bandit` as [issue B101](https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html), and it’s not possible to disable …

ci: add bandit to pre-commit hooks to check for common security issues

---

.pre-commit-config.yaml
MANIFEST.in
docs/source/index.rst
pyproject.toml

I added a bunch of new pre-commit hooks, and they reformatted the YAML and TOML files and found a few minor issues. Note, though, that said reformatting removed comments…
Bummer that I still haven’t figured out why three hooks run on `git push` when only one is configured to do so:
```
> git push --set-upstream origin pre-commit-improvements
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
tox......................................................................Passed
```

ci: add more pre-commit hooks, and clean up what the hooks flagged

---

pyproject.toml

commit_subject for semantic-release version command must have proper convention

chore: add “bump” type to release commits

---

.github/workflows/release-notifications.yaml
UPSTREAM_README.md

This change adds a new Github Action for the [Release Event](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#releaseevent): when a release is published (either manually through the Github website or through another Action) then this action sends out a Slack notification.
Because we don’t actually have a Slack workspace with this repository, the Action’s `slack` job is being skipped:
https://github.com/jenstroeger/python-package-template/blob/06319c75a537cf6df8d98bb71637c79b93e7ced0/.github/workflows/release-notifications.yaml#L8-L10
For now this PR is a **Draft** because we should probably document this feature in the [README.md](https://github.com/jenstroeger/python-package-template/blob/main/UPSTREAM_README.md)…

ci: add Release Notification action

---

.github/dependabot.yaml

Changes the Dependabot configuration to run the checks weekly instead of daily. Also changes the `fix` commit message scopes to `chore`.

chore: adjust Dependabot configuration

---

.github/workflows/check-and-release-main.yaml
setup.py

This PR installs the `wheel` package which is necessary for running `python setup.py bdist_wheel` ([make dist](https://github.com/jenstroeger/python-package-template/blob/add-wheel/Makefile#L100)) on latest version of Ubuntu. It also adds new steps to the CI workflow to test the the build.

fix: fix "make dist" failing on latest version of Ubuntu

---

.github/workflows/check-and-release-main.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/pull-request.yaml
.github/workflows/release-notifications.yaml
.github/workflows/scorecards-analysis.yaml
UPSTREAM_README.md

This PR adds [Scorecards security Actions workflow](https://github.com/ossf/scorecard-action), which analyzes the repo for various supply-chain security issues.
Closes #32

feat: add scorecards analysis workflow

---

MANIFEST.in
SECURITY.md
UPSTREAM_README.md
UPSTREAM_SECURITY.md
src/package/__init__.py

Based on code-scanning feedback for https://github.com/jenstroeger/python-package-template/security/code-scanning/36 and issue https://github.com/jenstroeger/python-package-template/issues/13, this change [adds a security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) to our template repo.

chore: add security policy, elaborate on test policy

---

.pre-commit-config.yaml
UPSTREAM_README.md
pyproject.toml

Thank you @travisjungroth for https://github.com/jenstroeger/python-package-template/pull/77#issuecomment-1152987935, this change adds [Bandit](https://github.com/PyCQA/bandit) as a git commit hook as per https://github.com/PyCQA/bandit/issues/902#issuecomment-1132322452.

ci: add Bandit security checker to git commit hooks

---

.github/workflows/check-and-release-main.yaml
UPSTREAM_README.md

Note that this fix merges directly into the `main` branch to address [this Release Action failure](https://github.com/jenstroeger/python-package-template/runs/6647674368?check_suite_focus=true). For more discussion on the problem and how to resolve it, see https://github.com/relekang/python-semantic-release/issues/311#issuecomment-1157270026.
TBH, I’m tempted to amend this change to commit https://github.com/jenstroeger/python-package-template/commit/5c8a47f13c26d727fea022a33b8c3baf87f7bbcd (the breaking change at the current HEAD of `main`).

fix(ci): use dedicated RELEASE_TOKEN for Release Action job

---

.flake8
.pre-commit-config.yaml
pyproject.toml
src/package/something.py

Poking through a few other packages I came across these `flake8` plugins that I think are useful to add:
- [bugbear](https://github.com/PyCQA/flake8-bugbear)
- [comprehensions](https://github.com/adamchainz/flake8-comprehensions)
- [mutable](https://github.com/ebeweber/flake8-mutable) (somewhat dated though)
- [noqa](https://github.com/plinss/flake8-noqa)
- [pytest-style](https://github.com/m-burst/flake8-pytest-style)
We’d also consider:
- [scream](https://github.com/MartinThoma/flake8-scream)
- Review this list of [Awesome Flake8 Plugins](https://github.com/DmytroLitvinov/awesome-flake8-extensions)

ci: add a bunch of useful Flake8 plugins to git commit hooks

---

.pre-commit-config.yaml
pyproject.toml

We should’t pin `black` to a particular Python version because the user may run a different version than pinned. Black is capable of “auto-discovery” ([docs](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options)):
```
-t, --target-version [py33|py34|py35|py36|py37|py38|py39|py310]
Python versions that should be supported by
Black's output. [default: per-file auto-
detection]
```
So hopefully the auto-discovery applies to the Python version as well.

fix: don’t pin Black to a particular Python version

---

pyproject.toml

Refs: d7956486a9d8d7a5292433a34fe88e0c319011dc

fix: bump min pytest version according to the "test" dependencies

---

pyproject.toml

Remove the [`max-module-lines`](https://pylint.pycqa.org/en/1.9/technical_reference/features.html#id8) setting because it defaults to 1000 anyway, and add a missing [`too-many-lines`](https://pylint.pycqa.org/en/1.9/technical_reference/features.html#id9) which overrides the max lines anyway.

chore: remove duplicate pylint settings

---

Makefile

Which also raises the question: do we want to handle the source and binary distribution separately? Now that we switched to `flit` as a build core (see PR https://github.com/jenstroeger/python-package-template/pull/208), we could just use [`flit build`](https://flit.pypa.io/en/latest/cmdline.html#flit-build) to build both…

feat: consolidate sdist and wheel into a single build target

---

.pre-commit-config.yaml

This leaves only pytest and commitizen without an explicitly set configuration file:
- pytest offers a [`-c` option (no long-option equivalent)](https://docs.pytest.org/en/latest/reference/customize.html#finding-the-rootdir) from where to load a configuration file, but seems quite explicit about determining its own root dir (and config file) automatically; and
- commitizen doesn’t provide a way to configure it ([docs](https://github.com/commitizen-tools/commitizen#help), [code](https://github.com/commitizen-tools/commitizen/blob/afa0d93544405bb0a871b5072e0a814720d933be/commitizen/cli.py#L27-L39)).
So we’re good with providing explicit configurations? 🤓

chore: add settings path to isort in pre-commit configuration

---

pyproject.toml

The two plugins, I think, are generally useful in a CI/CD development & test environment:
- https://github.com/MobileDynasty/pytest-env
- https://github.com/yashtodi94/pytest-custom_exit_code
Unfortunately both are somewhat dated…

feat: add pytest-env and pytest-custom-exit-code plugin support

---

Makefile
UPSTREAM_README.md

A few new goals which, I think, make daily developer life a little easier.
If we consider the Makefile as an interface of this repo (which it kinda is) then this is a breaking change 🤔

feat!: replace the Makefile’s quick-check goal with check-code

---

.pre-commit-config.yaml
MANIFEST.in
pyproject.toml

Following up on our Slack conversation and issue https://github.com/pypa/flit/issues/565, this change fixes `flit`’s source distribution.
Interestingly installing the `.tar.gz` sdist file fails:
```
> pip install /path/to/template/dist/package-1.6.1.tar.gz 
Processing /path/to/template/dist/package-1.6.1.tar.gz
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [29 lines of output]
Traceback (most recent call last):
File "/.../T/pip-build-env-n3xxqt2l/overlay/lib/python3.9/site-packages/flit_core/config.py", line 273, in description_from_file
with desc_path.open('r', encoding='utf-8') as f:
File "/.../3.9/lib/python3.9/pathlib.py", line …
```

fix: flit doesn’t support MANIFEST.in, fix sdist accordingly

---

.pre-commit-config.yaml

If the `src/package/` folder contains files other than Python, some of the code checkers complain. So, this change constrains the files passed to the hook to Python files only.
The [documentation](https://pre-commit.com/#filtering-files-with-types) suggests
```yaml
types: [file, python]
```
though.

chore: add file types to some code checking hooks

---

Makefile

Calling `make` without any arguments makes the first goal in the Makefile because we did not specify a [`.DEFAULT`](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html). That currently is the `venv` goal to install the Python virtual environment.
I think it makes<sup>*</sup> more sense (and is [common](https://stackoverflow.com/questions/27242905/makefile-all-vs-default-targets)) to make `all` that default goal such that running just `make` makes the entire package.
This change hoists `all` up to be the first goal in the Makefile.
—————
<sup>*</sup> Pun intended.

fix: default goal for make should be to build the entire package

---

.github/workflows/build.yaml
Makefile
README.md

This actually works 🤓 First, we build the assets:
```
> make dist
flit build --setup-py --format wheel
flit build --setup-py --format sdist
python -m zipfile -c dist/package-2.2.0-docs-html.zip docs/_build/html
echo 1659672848 > dist/package-2.2.0-build-epoch.txt
```
and check the wheel’s hash so we can compare it later:
```
> md5sum dist/package-2.2.0-py3-none-any.whl
081aaf0482704b78950854690c8b30d7  dist/package-2.2.0-py3-none-any.whl
```
Then touch a source file so it has a different time stamp but the same content:
```
> touch src/package/something.py
```
Next, build the package _again_ but this time using the time stamp from the previous build:
```
> SOURCE_DATE_EPOCH=1659672848 make dist
flit build --setup-py --format wheel
Zip timestamps will be from SOURCE_DATE_EPOCH: 2022-08-05 …
```

feat: always create a reproducible build with `make dist`

---

Makefile

Following up on our conversation about failing `hashin` calls: the failure is legit. By default, [`pip list`](https://pip.pypa.io/en/stable/cli/pip_list/) makes additional noise:
```
> pip list --format freeze 
alabaster==0.7.12
...
zipp==3.8.1
[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
```
which `hashin` interprets as packages and attempts to generate hashes for. That doesn’t work out well, of course<sup>*</sup> 🤦🏻‍♂️ 
```
zipp==3.8.1 \
--hash=sha256:05b45f1ee8f807d0cc928485ca40a07cb491cf092ff587c0df9cb1fd154848d2 \
--hash=sha256:47c40d7fe183a6f21403a199b3e4192cca5774656965b0a4988ad2f8feb5f009
a==1.0 \
--hash=sha256:ac14dc3a69f5746f06fd72fd2f2dace84bc07247182b3b117eaaa14dfd5fb0cd
of==1.0.1 \ …
```

fix: disable noise when freezing the current venv

---

.github/workflows/build.yaml

chore(ci): use a runner’s global Python install instead of venv

---

.github/workflows/build.yaml

It’s probably enough to build the `requirements.txt` file and the SBOM only when we create a release…
@behnazh we currently build and upload the release artifacts with _every run_ of the workflow, and only the “Update release tag” step is guarded
https://github.com/jenstroeger/python-package-template/blob/c7541754294c634cd807068ffaf37bd0279cbb52/.github/workflows/build.yaml#L124
Should we limit the other steps too?

ci: build requirements.txt and SBOM artifacts only on release

---

README.md

The two spaces are necessary to add the line break, or else the TOC entry is on the same line as its predecessor—see the TOC in the [current README](https://github.com/jenstroeger/python-package-template/blob/c7541754294c634cd807068ffaf37bd0279cbb52/README.md).

docs: fix typo in TOC

---

.github/dependabot.yaml

We can assign one or more reviewers to PRs that Dependabot opens ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers)), and perhaps it’s worthwhile adding to the configuration? Not sure if we want to comment that out or leave it as an active feature.
We we add this change, we probably should document it in our README.

chore: add reviewers to the Dependabot configuration

---

Makefile

This is to be consistent with the remainder of the Makefile where we’ve established the convention that the Python virtual environment is the `.venv/` folder. The `VIRTUAL_ENV` environment variable, in contrast, is used only to check whether a virtual env was _activated_ but not to determine its location.

chore: use actual .venv directory name in nuke-caches Makefile recipe

---

Makefile

Comments inside the recipe are printed when the recipe executes, which is actually quite distracting. And unintended. Hoisting the comment out fixes that eyesore 😁

chore: hoist comment out of the recipe shell into the Makefile proper

---

.github/workflows/pull-request.yaml

Following up on comment https://github.com/jenstroeger/python-package-template/pull/224#issuecomment-1217361225, this change provides a fix.
I tested it in a private repo against a PR in that same private repo, but wasn’t able to test it for a fork because that fork was private and belonged to another org (because I can’t fork my own repos). I think we’ll have to test this across forked public repositories for now.

fix(ci): allow PR Action to check commits across branches of forks

---

Makefile

Refs: 0cc789de1d737b474f16e5b477829c64b26022fd, caba574e55702c29aedca47614787f153f26a16f, 2a24e248a543f5e58020a7b522c73adbc3271d47

fix: fix Makefile’s check for goals that require a virtual environment

---

.pre-commit-config.yaml

This comes in handy if `mypy` crashes.

chore: show traceback if mypy boinks

---

Makefile

We use the `requirements.txt` file as a distribution artifact, so we should delete it as part of the distribution too. Methinks.

fix: remove requirements.txt when cleaning the distribution artifacts

---

Makefile

This is particularly important on Windows hosts. For more background on this change: https://github.com/pypa/pip-audit/issues/365#issuecomment-1238851482

fix: remove trailing CR-LF from package spec when building requirements

---

pyproject.toml

We already do that when running `pytest` through the git hooks:
https://github.com/jenstroeger/python-package-template/blob/f41b0e6a46061081370253b9ac17a1b62b5c85dc/.pre-commit-config.yaml#L156

chore(test): enable PYTHONWARNINGS when running pytest alone

---

.github/codeql/codeql-config.yaml
.github/dependabot.yaml
.github/workflows/build.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/pull-request.yaml
.github/workflows/release-notifications.yaml
.github/workflows/release.yaml
.github/workflows/scorecards-analysis.yaml

One more thought: it looks like Github [is not able to share environment variables _between_ workflows](https://docs.github.com/en/actions/learn-github-actions/environment-variables). But I wonder if perhaps we should move “global” variables like this:
https://github.com/jenstroeger/python-package-template/blob/ceee4a7b803747f9e168f188227345685d984c5b/.github/workflows/release.yaml#L14-L17
to the only step that actually uses them
https://github.com/jenstroeger/python-package-template/blob/ceee4a7b803747f9e168f188227345685d984c5b/.github/workflows/release.yaml#L57-L61
Simply for the sake of tightening the scope.

chore(ci): reformat and split up steps to improve debugging & readability

---

Makefile

Use [simply expanded variables](https://www.gnu.org/software/make/manual/html_node/Flavors.html) for _all_ variable expansions because there’s no need to get any more sophisticated.

fix: use simple expansion consistently for all Makefile variables

---

Makefile

I stumbled upon issues when I played with the [`.ONESHELL:` special target](https://www.gnu.org/software/make/manual/html_node/One-Shell.html):
```
> make audit
make: /usr/bin/env bash: No such file or directory
...
```
Documentation on this is a little sparse, I thought.
<hr>
I also think we should consider using the special target `.ONESHELL:`: it runs the entire recipe in a _single_ shell which would allow us to set & use environment variables within that recipe. So far we’ve danced around `make` running every recipe line in its own shell, and that has complicated some of our process. In that context, it would also make sense to discuss [`.EXPORT_ALL_VARIABLES:`](https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html).
There’s also an option to [silence …

fix: a Makefile’s SHELL variable is not an executable shebang

---

pyproject.toml

See also: https://github.com/pytest-dev/py/issues/287#issuecomment-1290407715
This PR supersedes https://github.com/jenstroeger/python-package-template/pull/353

fix: update pytest to drop dependency on vulnerable py package

---

.github/workflows/release.yaml

This PR decouples the release and provenance generation and allows the release to proceed even if provenance generation fails.

refactor(ci): allow release when provenance generation fails

---

Makefile

It might happen that a user runs
```
(project) ~/some/path > deactivate
~/some/path > make venv
```
in which case we want to exit gracefully instead of installing a new venv over the existing one.

fix: exit Makefile gracefully if an inactive venv was found

---

Makefile

Just like here
https://github.com/jenstroeger/python-package-template/blob/2adf30a7250ce8a6061f325f7aac2ad78777492a/Makefile#L36-L37
we want to make sure we determine an activated virtual env correctly by its environment variable, not whether a path & file exists (which is no indicator as to if the venv was actually activated).

fix: determine an activated venv correctly when running make

---

Makefile

Note that all `make check` variants run their `pre-commit` hooks on _unstaged_ files by using the [`--all-files`](https://pre-commit.com/#pre-commit-run) command line option:
https://github.com/jenstroeger/python-package-template/blob/f41b0e6a46061081370253b9ac17a1b62b5c85dc/Makefile#L157-L166
However, running `make test` does not specify that option
https://github.com/jenstroeger/python-package-template/blob/f41b0e6a46061081370253b9ac17a1b62b5c85dc/Makefile#L170-L171
and thus _stashes_ changes before running:
```
> make test
pre-commit run pytest --hook-stage push
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /path/to/.cache/pre-commit/patch1666240262-62070.
Run unit tests...........................................................Passed
- hook id: pytest
- …
```

fix: run pytest hook on unstaged files

---

.github/workflows/build.yaml
.github/workflows/pr-conventional-commits.yaml
.github/workflows/release.yaml

Ran [actionlint](https://github.com/rhysd/actionlint) which used [shellcheck](https://www.shellcheck.net/), and fixed the warnings. (See also issue https://github.com/jenstroeger/python-package-template/issues/58.)

fix(ci): fix actionlint warnings

---

Makefile

So… calling `make nuke` usually fails because `deactivate` can’t be found when running `make`. That is because `deactivate` is actually a function sourced by the `activate` script
```shell
> type -t deactivate 
function
```
and therefore it’s not available in the subprocess that runs the shell in the Makefile. This change prevents that failure, and instead just aborts `make` cleanly if the venv is activated.

fix: don’t nuke an activated virtual environment

---

.github/workflows/release.yaml

It’s becoming really quite miserable how often those SLSA folks break their Github Action, and how carelessly they’re versioning it. Apparently, any release [older than v1.2.2](https://github.com/slsa-framework/slsa-github-generator/releases) is now deprecated.

fix(ci): update deprecated SLSA provenance generator, again

---

Makefile

Thank you @behnazh for noticing the regression with [v2.4.1](https://github.com/jenstroeger/python-package-template/releases/tag/v2.4.1), introduced by PR https://github.com/jenstroeger/python-package-template/pull/346. The problem is (still and again 🤦🏻‍♂️) that we don’t set up a venv in a Github runner and therefore we shouldn’t rely on the `VIRTUAL_ENV` environment variable.
This change expands the Python command so that the command _always_ returns a package version string (which may be `"unknown"`) instead of failing the `import package`.
I think it’s safe to expect `"unknown"` for `make venv` (or its Action equivalent)
https://github.com/jenstroeger/python-package-template/blob/7bf474b781efa1fb0e69dcf31f968675695f10bc/.github/workflows/build.yaml#L70-L71
and `make setup` …

fix: determine package version even in deactivated venv

---

.github/workflows/_release-notifications.yaml
.github/workflows/release.yaml
README.md

If triggered by the [`release[released]`](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#releaseevent) event then the [Release Notification workflow](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/release-notifications.yaml) ([code](https://github.com/jenstroeger/python-package-template/blob/7bf474b781efa1fb0e69dcf31f968675695f10bc/.github/workflows/release.yaml#L137)) starts running before the [Release workflow](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/release.yaml) finishes. That can lead to a race condition where the release artifacts of the Release workflow are not yet available to workflows triggered by the `release[released]` event.
Using a reusable workflow addresses …

fix(ci): make Release Notification a reusable workflow to avoid artifact race

---

.github/workflows/release.yaml

From the [`base64` man page](https://linux.die.net/man/1/base64):
```
-d, --decode
decode data
```

chore(ci): use long command-line option to improve readability

---

README.md

This issue has been around for a while, it seems, and is also addressed by PR https://github.com/jenstroeger/python-package-template/pull/396.

docs: fix incorrect link target

---

.github/workflows/release.yaml

Rerunning the Release workflow may cause a re-upload of the build-artifacts. By default [`twine`](https://twine.readthedocs.io/) fails when uploading an existing package, so let’s allow that so that the workflow can rerun successfully.

chore(ci): add twine command line argument to rerun workflow more easily

---

.flake8
pyproject.toml

Both `pylint`’s [line-too-long](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/line-too-long.html) check and `flake8`’s [E501](https://www.flake8rules.com/rules/E501.html) are hard limits—one character over the configured line limit (120 characters in our case) triggers the error.
Bugbear’s [B950](https://github.com/PyCQA/flake8-bugbear) is more flexible in that…
> This is a pragmatic equivalent of pycodestyle's E501: it considers "max-line-length" but only triggers when the value has been exceeded by more than 10%. You will no longer be forced to reformat code due to the closing parenthesis being one character too far to satisfy the linter. At the same time, if you do significantly violate the line length, you will receive a message that states what the actual limit …

fix: line-length checks are now a bit more tolerant using Bugbear only

---

.pre-commit-config.yaml
pyproject.toml

We should not configure [Python warnings](https://docs.python.org/3/library/warnings.html) for `pytest` in two different places, esp. if `pytest` sports a [`filterwarnings` configuration option](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-filterwarnings).

refactor(test): configure warnings for pytest through pyproject.toml only

---

pyproject.toml

Personally I always found the “long” `pytest` tracebacks intrusive and obscure, and much prefer to work with Python’s native traceback style. See also the [docs](https://docs.pytest.org/en/7.2.x/how-to/output.html#modifying-python-traceback-printing).

chore: collapse verbose pytest tracebacks to native Python format

---

Makefile
pyproject.toml

This PR updates `cyclonedx-bom` Python module and uses `cyclonedx-py` instead of the deprecated `cyclonedx-bom` CLI command.
For more information see: https://github.com/CycloneDX/cyclonedx-python/releases/tag/v3.11.0.

chore(deps): update cyclonedx-bom and remove deprecated CLI command

---

pyproject.toml

I didn’t find a long option version for `-vv` — `--verbose --verbose` didn’t work and neither did changing the argument to `--verbosity` (although I would have thought so from the [`pytest` arg parsing](https://github.com/pytest-dev/pytest/blob/310b67b2271cb05f575054c1cdd2ece2412c89a2/src/_pytest/terminal.py#L116-L152) or [the docs](https://docs.pytest.org/en/7.1.x/how-to/output.html#verbosity)).

fix(test): make pytest a little more verbose when tests fail

---

Makefile

Fixes #484 
We still have a problem which might not really be one: timezones. When we pass the [`SOURCE_DATE_EPOCH`](https://flit.pypa.io/en/stable/reproducible.html) environment variable then its value is an [epoch](https://en.wikipedia.org/wiki/Unix_time) which, by definition, is in UTC. However, `flit` sets the package files’ date to _that_ value without accounting for the timezone of the host. For example, with a timestamp of `1677448329` (26. Feb 2023 9:52:09 PM UTC, or 27 Feb 2023 7:52:09 AM AEST) the packaged files receive the following date:
```
> ll package/
total 16K
-rw-r--r-- 1 savage admin 385 Feb 26 21:52 __init__.py
-rw-r--r-- 1 savage admin 496 Feb 26 21:52 __main__.py
-rw-r--r-- 1 savage admin  80 Feb 26 21:52 py.typed
-rw-r--r-- 1 savage admin 268 Feb 26 21:52 …
```

fix(ci): ensure correct epoch for packaged files to enable reproducible builds

---

README.md
pyproject.toml

It’s probably a good idea to enable [branch coverage measurement](https://coverage.readthedocs.io/en/7.1.0/branch.html):
```
Name                       Stmts   Miss Branch BrPart  Cover   Missing
----------------------------------------------------------------------
src/package/__init__.py        1      0      0      0   100%
src/package/something.py       4      0      2      0   100%
----------------------------------------------------------------------
TOTAL                          5      0      2      0   100%
```

test: add branch coverage monitoring the to code coverage report

---

.github/workflows/sync-with-upstream.yaml

Considering we have the previous version of the template:
https://github.com/jenstroeger/python-package-template/blob/6b337a397b37d47e26f9b2889882e6e996b8aa9d/.github/workflows/sync-with-upstream.yaml#L49-L50
would it make sense to check if a branch for that previous version exists, and close the PR and delete that now older branch? Or, if not, mark the older PR as [a duplicate of the new PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate)?
The new branch that’s being opened should include all changes from that older branch 🤔
Also, should we add [`--reviewer`](https://cli.github.com/manual/gh_pr_create#options) to the PR creation?

fix(ci): add docs/source/ folder to the excludes of the Sync Upstream workflow

---

.flake8

There’s much discussion on how to make Black and Flake8 play nice with each other. There’s also much discussion on how well Flake8 implements [PEP8](https://peps.python.org/pep-0008/).
First, we’ve been using the [`ignore`](https://flake8.pycqa.org/en/6.0.0/user/options.html#cmdoption-flake8-ignore) option
https://github.com/jenstroeger/python-package-template/blob/0b40f48f607bf1a69b8f4963dea3105ee0f3bf93/.flake8#L8
which defaults to `E121,E123,E126,E226,E24,E704,W503,W504`. By providing our own we essentially re-_enabled_ these other options. Then there is [`extend-ignore`](https://flake8.pycqa.org/en/6.0.0/user/options.html#cmdoption-flake8-extend-ignore) which _extends_ to default list, rather than replacing it.
Second, considering the [Using _Black_ with other …

fix: make Black, Flake8, Sphinx play nice together by tweaking a few Flake8 settings

---

.github/workflows/_wiki-documentation.yaml
.github/workflows/sync-with-upstream.yaml
.pre-commit-config.yaml
Makefile
README.md

This PR adds [actionlint](https://github.com/Mateusz-Grzelinski/actionlint-py) as a pre-commit hook to lint and check GitHub Actions workflows. The check runs using `make check-actionlint`. 
The new `actionlint` hook detects errors that were also addressed in https://github.com/jenstroeger/python-package-template/pull/482 and https://github.com/jenstroeger/python-package-template/pull/493, which had to be fixed here for the workflows to succeed.

feat: add actionlint hook and fix current errors

---

.github/workflows/_generate-rebase.yaml
.github/workflows/release.yaml
README.md

Fixes https://github.com/jenstroeger/python-package-template/issues/266.
Tagging @eduardocardoso because he wrote most of the original workflow.

feat(ci): add a Rebase Branch workflow to rebase staging on top of main after a package was published

---

pyproject.toml

See also https://github.com/dgilland/pydash/issues/197

fix(deps): temporarily pin typing-extensions deps, to avoid breaking the sphinxnotes-markdown-builder package

---

.github/workflows/sync-with-upstream.yaml

Fixes https://github.com/jenstroeger/python-package-template/issues/472.
Tagging @eduardocardoso because he wrote most of the original workflow.
@behnazh Do we want to add issue https://github.com/jenstroeger/python-package-template/issues/509 to this change as well?

fix(ci): improve automatic template synchronization

---

docs/Makefile

This PR changes the Sphinx configuration to treat warnings as errors, which helps to detect documentation issues in CI tests.

feat: treat Sphinx docs warnings as errors

---

.pre-commit-config.yaml
README.md
docs/source/index.rst
pyproject.toml
src/package/something.py

So far we’ve had [doctest](https://docs.python.org/3/library/doctest.html) support somewhat configured, but it wasn’t actually used because doctest didn’t run. This PR adds full support for running doctest on both
- Python package docstrings, and
- `.rst` files in the documentation.
Tasks to discuss and (maybe) to add to this PR:

feat: run doctest as part of running tests, which collects doctests from both the package’s doc strings and the package documentation

---

.pre-commit-config.yaml

Note that the arg of 500kb is the [default](https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-added-large-files) that I added for documentation’s sake.

fix: change git hook to check for large files on commit, instead of push

---

.github/workflows/release.yaml

feat(ci): switch from building the SLSA provenance generator to using the pre-built version to improve runtime performance

---

.github/workflows/_build.yaml
.github/workflows/_wiki-documentation.yaml
.github/workflows/release.yaml
.github/workflows/scorecards-analysis.yaml

The provenance generator GitHub Action [generator_generic_slsa3.yml](https://github.com/jenstroeger/python-package-template/blob/92b86565b015e5b36e18adcea21b0c41c4997ce5/.github/workflows/release.yaml#L178) is not compatible with `actions/download-artifact@v4` yet. We need to make sure these two Actions and `actions/upload-artifact` are all compatible.
This PR reverts `actions/download-artifact` and  `actions/upload-artifact` GitHub Actions to v3. We will update them to v4 when the next version of generator_generic_slsa3.yml that will be compatible with `actions/download-artifact@v4` is released. See this relevant https://github.com/slsa-framework/slsa-github-generator/issues/3068.

fix(deps-dev): revert artifact download and upload GitHub Actions to v3

---

.github/workflows/_build.yaml
.github/workflows/release.yaml
.github/workflows/scorecards-analysis.yaml

The `slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0` GitHub Action requires `actions/upload-artifact@v4` Action. See the [CHANGELOG](https://github.com/slsa-framework/slsa-github-generator/blob/v2.0.0/CHANGELOG.md#v200-breaking-change-upload-artifact-and-download-artifact) for more information.

fix(ci): use actions/upload-artifact@v4 to be compatible with slsa provenance action

---

.github/workflows/release.yaml

This actually happened in a downstream repository where another package was added to the repository and that new package’s version was different than the repo’s — then `cz bump` failed silently for that new package and CI proceeded just fine.

fix(ci): commitizen and CI should fail if the bumped version strings contain inconsistent version numbers

---

Makefile

So, here’s the thing. Python 3.10.14 and 3.11.9 create a venv like so[^1]
```
~ > python3.10 -m venv test
~ > . test/bin/activate
(test) ~ > pip list
Package    Version
---------- -------
pip        23.0.1
setuptools 65.5.0
```
The problem is that setuptools v65.5.0 and below are subject to https://github.com/advisories/GHSA-r9hx-vwmv-q579, and should be — like pip — updated to the latest version when we set up the venv. If not, there’s a good chance that `make audit` will trigger if no other package happens to update the setuptools package…
In this package we’ve been lucky because of an indirect dependency (e.g. [here](https://github.com/jenstroeger/python-package-template/actions/runs/10556221766/job/29241332587?pr=789#step:7:100)) and our [eager update …

fix(ci): also update setuptools when setting up the virtual environment

---

.github/workflows/_build.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/pr-conventional-commits.yaml
.github/workflows/release.yaml
Makefile
README.md
pyproject.toml

Adding support for [Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html).
@behnazh I’ve not yet dropped support for Python 3.10 because we’re using it in other projects, though I think I’m ok with moving to 3.12 as the minimal supported version because both 3.10 ([release schedule](https://peps.python.org/pep-0619/#lifespan)) and 3.11 ([release schedule](https://peps.python.org/pep-0664/#lifespan)) are now considered legacy.

feat: add support for Python 3.13

---

.pre-commit-config.yaml

Turns out that the isort hook configuration [here](https://github.com/PyCQA/isort/blob/main/.pre-commit-hooks.yaml) wants to run the isort hook at different times — so we pin it down to pre-commit only.

fix: don’t attempt to sort imports on `git push` (they must already be sorted)

---

pyproject.toml

Documented [here](https://docs.pytest.org/en/6.2.x/usage.html#profiling-test-execution-duration) the argument `0` prints durations for all tests.

feat(test): add the duration of tests to the printed test summary

---

README.md

Should’ve been part or PR https://github.com/jenstroeger/python-package-template/pull/852 🤦🏻‍♂️
Refs: a788e3341ce99472ab7ac7f30a8d6176e3ae7a41

docs: update README with the latest changes

---

pyproject.toml
tests/test_something.py

The [pytest-cases](https://smarie.github.io/python-pytest-cases/) plugin is very useful to separate test case generation from test function, a separation that’s not as explicit in pytest itself. I think with PR https://github.com/smarie/python-pytest-cases/issues/319 this change could offer quite flexible & powerful testing.

feat(test): add the pytest-cases package and a simple example of how to use it

---

pyproject.toml

Thing is, we invoke `isort` via the pre-commit git hooks and that hook passes a list of files to `isort` in the command line. We now have to tell `isort` to filter those files by the settings in the configuration or else _all_ files will be sorted. For details see the [Filter files](https://pycqa.github.io/isort/docs/configuration/options.html#filter-files) section in the `isort` docs.

fix: make sure isort skips over files listed as such in the pyproject.toml tool configuration

---

pyproject.toml

@behnazh the sdist still contains the `pyproject.toml` file:
```
> tar tvf dist/package-2.16.0.tar.gz 
-rw-r--r-- 0/0            1063 2025-06-03 00:17 package-2.16.0/LICENSE.md
-rw-r--r-- 0/0           28836 2025-06-03 00:17 package-2.16.0/README.md
-rw-r--r-- 0/0            8257 2025-06-03 00:17 package-2.16.0/pyproject.toml
-rw-r--r-- 0/0             386 2025-06-03 00:17 package-2.16.0/src/package/__init__.py
-rw-r--r-- 0/0             496 2025-06-03 00:17 package-2.16.0/src/package/__main__.py
-rw-r--r-- 0/0              80 2025-06-03 00:17 package-2.16.0/src/package/py.typed
-rw-r--r-- 0/0             520 2025-06-03 00:17 package-2.16.0/src/package/something.py
-rw-r--r-- 0/0            1352 1970-01-01 10:00 package-2.16.0/setup.py
-rw-r--r-- 0/0           31320 1970-01-01 10:00 …
```

fix: remove various repo files that leaked into the sdist of the package

---

.github/workflows/release.yaml

This PR uses the `head_commit` object from the [GitHub context object](https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context) for checking the `bump` message. This approach provides a cleaner and more reliable way to detect version bump commits.

build: use head_commit object for checking the bump message
