.pre-commit-config.yaml, mypy.ini
Closes #38. For more details, see the linked issue.
=> fix: git hook configuration didn’t match package paths anymore

UPSTREAM_README.md, commitlint.rules.js
=> fix: typos in documentation because we renamed YAML files

UPSTREAM_README.md
Refs: b172bcb52600d7fd656b4a9d64b3dbbc6ef52c8e
=> docs: improve comment to explain standalone-use of this package

UPSTREAM_README.md
Closes #124, for more information see that issue.
=> docs: mention cost impact for different Action runners

.pre-commit-config.yaml
Closes #113, for more information see that issue.
=> fix: pass pylint configuration to pylint explicitly

mypy.ini
Closes #195. Please see that issue for details.
=> chore: disable mypy incremental mode

setup.py
See also https://github.com/jenstroeger/python-package-template/pull/181#issuecomment-1118000563
=> chore(deps): update to pytest 7

.github/workflows/check-and-release-main.yaml
Thanks you @lecram for looking into this!
=> fix(ci): enable Release Action for protected branches

.pre-commit-config.yaml
Refs: 4fd3e830a03b0bbe74dddda06034776161b942f4
=> chore: remove stale tox related comment

pyproject.toml
Refs: 7c53de37b11a10def2775c5c7658a1cb206cd990
=> chore: shuffle comments into the right place

.github/workflows/check-and-release-main.yaml, pyproject.toml
Closes #222, see the discussion that related issue.
=> fix(ci): run all Actions except the Release job on the release commit

Makefile
Refs: be7ba064192624558fbf97c2dea37a7189ccb3ad
=> chore: remove cruft left over from previous Makefile changes

Makefile
For more details, see [this section](https://flit.pypa.io/en/latest/reproducible.html). Should we add a link to that document to the Makefile for reference?
=> feat: warn if generated builds are not reproducible

Makefile
=> fix: create empty pip.conf file inside a new virtual environment

.pre-commit-config.yaml, Makefile, pyproject.toml
As [discussed on Slack](https://bookalope.slack.com/archives/D028J9D3GLE/p1660873570492389).
=> chore: configure git hooks using pre-commit config file instead of cmd line

.github/workflows/release.yaml
=> chore(ci): change the user/email for release commits to `jenstroeger`

Makefile
Thank you @behnazh for waiting patiently 😁
=> chore: use PACKAGE_NAME and PACKAGE_VERSION consistently in Makefile

README.md
Refs: 781485e207376990aa54c7bc042b3c6eb74f8934
=> fix(docs): update README with correct CHANGELOG setup instructions

.github/workflows/pr-change-set.yaml, .github/workflows/pr-conventional-commits.yaml
For more background see issue https://github.com/jenstroeger/python-package-template/issues/330.
=> fix(ci): trigger PR actions for all target branches

.github/workflows/scorecards-analysis.yaml
See also https://github.com/ossf/scorecard/issues/2408#issuecomment-1294514119 andd [this example](https://github.com/flutter/flutter/blob/ea0ddc94ccc63cec77bcac3ef02832806adcd667/.github/workflows/scorecards-analysis.yml#L21-L22).
=> fix(ci): as of v2 Scorecard requires extra permissions

README.md
Refs: 781485e207376990aa54c7bc042b3c6eb74f8934
=> docs: remove references to Action we long stopped using

Makefile
Refs: 22a020ade021e598f1945cfe7f1a975daca72b03
=> fix: incorrect folder name for pytest

.github/workflows/codeql-analysis.yaml, .github/workflows/pr-conventional-commits.yaml, .github/workflows/release.yaml, .github/workflows/scorecards-analysis.yaml, .pre-commit-config.yaml, pyproject.toml
This change includes all currently open Dependabot PRs.
=> chore(deps): update dependent tools and packages

.gitattributes
The .gitattributes file follows the best practices from https://rehansaeed.com/gitattributes-best-practices/
This is for #389.
=> feat: Add .gitattributes file

.github/workflows/release.yaml
=> fix(ci): don’t fail bump job if there are no commits to bump

README.md
Refs: ef0a354185ee42a86308faf0bbe8aba24c2342ba
=> chore(docs): improve feature list item

.github/workflows/sync-with-upstream.yaml, README.md
This PR adds a GitHub Actions workflow, which checks for new releases in this template repo daily and creates a pull request in the downstream repo.
=> feat: add a workflow to create sync PRs

.github/workflows/sync-with-upstream.yaml, CODEOWNERS
=> feat: add CODEOWNERS file to the repository

.pre-commit-config.yaml, README.md
=> feat: add flake8-pyi plugin to check .pyi files (if any)

LICENSE.md, docs/source/conf.py
Same as PR https://github.com/jenstroeger/python-package-template/pull/265.
=> chore: update copyright years

pyproject.toml
Refs: e64682eba459de0478e383b7b9f5845e92699bc9
=> chore(deps): loosen pin for the typing-extensions package

pyproject.toml
=> feat: add perflint to find performance anti-patterns

.github/workflows/_build.yaml, .github/workflows/_generate-rebase.yaml, .github/workflows/_release-notifications.yaml, .github/workflows/_wiki-documentation.yaml, .github/workflows/pr-change-set.yaml, .github/workflows/release.yaml
The long awaited, once in a lifetime [beastly](https://en.wikipedia.org/wiki/Number_of_the_beast) PR!
This one is quite harmless though, perhaps somewhat controversial, but definitely requires a bit of conversation 😇
=> chore(ci): rename input and output options for workflows to improve consistency with Github

.github/workflows/release.yaml
Refs: f70fd7ce0139fb07c0f87132281d38c7417029e0
=> fix(ci): fix the artifact name for the Release workflow

.github/workflows/release.yaml
Refs: f70fd7ce0139fb07c0f87132281d38c7417029e0
=> fix(ci): fix the artifact name for the Release workflow (#733)

.pre-commit-config.yaml
Refs: 3e3172397e1c3de1e5a423e505fe11e657dfad98
=> chore(deps-dev): update pre-commit tools

Makefile
Redo PR https://github.com/jenstroeger/python-package-template/pull/793
=> fix(ci): also update setuptools when setting up the virtual environment
